// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package testpb is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	TestMessage
	TestRequest
	TestResponse
	CacheStats
	StatsResponse
	Empty
*/
package testpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestMessage struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	City             *string `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TestMessage) Reset()                    { *m = TestMessage{} }
func (m *TestMessage) String() string            { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()               {}
func (*TestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TestMessage) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

type TestRequest struct {
	Lower            *string `protobuf:"bytes,1,req,name=lower" json:"lower,omitempty"`
	RepeatCount      *int32  `protobuf:"varint,2,opt,name=repeat_count,json=repeatCount,def=1" json:"repeat_count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TestRequest) Reset()                    { *m = TestRequest{} }
func (m *TestRequest) String() string            { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()               {}
func (*TestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_TestRequest_RepeatCount int32 = 1

func (m *TestRequest) GetLower() string {
	if m != nil && m.Lower != nil {
		return *m.Lower
	}
	return ""
}

func (m *TestRequest) GetRepeatCount() int32 {
	if m != nil && m.RepeatCount != nil {
		return *m.RepeatCount
	}
	return Default_TestRequest_RepeatCount
}

type TestResponse struct {
	Value            *string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TestResponse) Reset()                    { *m = TestResponse{} }
func (m *TestResponse) String() string            { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()               {}
func (*TestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TestResponse) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type CacheStats struct {
	Items            *int64 `protobuf:"varint,1,opt,name=items" json:"items,omitempty"`
	Bytes            *int64 `protobuf:"varint,2,opt,name=bytes" json:"bytes,omitempty"`
	Gets             *int64 `protobuf:"varint,3,opt,name=gets" json:"gets,omitempty"`
	Hits             *int64 `protobuf:"varint,4,opt,name=hits" json:"hits,omitempty"`
	Evicts           *int64 `protobuf:"varint,5,opt,name=evicts" json:"evicts,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CacheStats) Reset()                    { *m = CacheStats{} }
func (m *CacheStats) String() string            { return proto.CompactTextString(m) }
func (*CacheStats) ProtoMessage()               {}
func (*CacheStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CacheStats) GetItems() int64 {
	if m != nil && m.Items != nil {
		return *m.Items
	}
	return 0
}

func (m *CacheStats) GetBytes() int64 {
	if m != nil && m.Bytes != nil {
		return *m.Bytes
	}
	return 0
}

func (m *CacheStats) GetGets() int64 {
	if m != nil && m.Gets != nil {
		return *m.Gets
	}
	return 0
}

func (m *CacheStats) GetHits() int64 {
	if m != nil && m.Hits != nil {
		return *m.Hits
	}
	return 0
}

func (m *CacheStats) GetEvicts() int64 {
	if m != nil && m.Evicts != nil {
		return *m.Evicts
	}
	return 0
}

type StatsResponse struct {
	Gets             *int64      `protobuf:"varint,1,opt,name=gets" json:"gets,omitempty"`
	CacheHits        *int64      `protobuf:"varint,12,opt,name=cache_hits,json=cacheHits" json:"cache_hits,omitempty"`
	Fills            *int64      `protobuf:"varint,2,opt,name=fills" json:"fills,omitempty"`
	TotalAlloc       *uint64     `protobuf:"varint,3,opt,name=total_alloc,json=totalAlloc" json:"total_alloc,omitempty"`
	MainCache        *CacheStats `protobuf:"bytes,4,opt,name=main_cache,json=mainCache" json:"main_cache,omitempty"`
	HotCache         *CacheStats `protobuf:"bytes,5,opt,name=hot_cache,json=hotCache" json:"hot_cache,omitempty"`
	ServerIn         *int64      `protobuf:"varint,6,opt,name=server_in,json=serverIn" json:"server_in,omitempty"`
	Loads            *int64      `protobuf:"varint,8,opt,name=loads" json:"loads,omitempty"`
	PeerLoads        *int64      `protobuf:"varint,9,opt,name=peer_loads,json=peerLoads" json:"peer_loads,omitempty"`
	PeerErrors       *int64      `protobuf:"varint,10,opt,name=peer_errors,json=peerErrors" json:"peer_errors,omitempty"`
	LocalLoads       *int64      `protobuf:"varint,11,opt,name=local_loads,json=localLoads" json:"local_loads,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *StatsResponse) Reset()                    { *m = StatsResponse{} }
func (m *StatsResponse) String() string            { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()               {}
func (*StatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StatsResponse) GetGets() int64 {
	if m != nil && m.Gets != nil {
		return *m.Gets
	}
	return 0
}

func (m *StatsResponse) GetCacheHits() int64 {
	if m != nil && m.CacheHits != nil {
		return *m.CacheHits
	}
	return 0
}

func (m *StatsResponse) GetFills() int64 {
	if m != nil && m.Fills != nil {
		return *m.Fills
	}
	return 0
}

func (m *StatsResponse) GetTotalAlloc() uint64 {
	if m != nil && m.TotalAlloc != nil {
		return *m.TotalAlloc
	}
	return 0
}

func (m *StatsResponse) GetMainCache() *CacheStats {
	if m != nil {
		return m.MainCache
	}
	return nil
}

func (m *StatsResponse) GetHotCache() *CacheStats {
	if m != nil {
		return m.HotCache
	}
	return nil
}

func (m *StatsResponse) GetServerIn() int64 {
	if m != nil && m.ServerIn != nil {
		return *m.ServerIn
	}
	return 0
}

func (m *StatsResponse) GetLoads() int64 {
	if m != nil && m.Loads != nil {
		return *m.Loads
	}
	return 0
}

func (m *StatsResponse) GetPeerLoads() int64 {
	if m != nil && m.PeerLoads != nil {
		return *m.PeerLoads
	}
	return 0
}

func (m *StatsResponse) GetPeerErrors() int64 {
	if m != nil && m.PeerErrors != nil {
		return *m.PeerErrors
	}
	return 0
}

func (m *StatsResponse) GetLocalLoads() int64 {
	if m != nil && m.LocalLoads != nil {
		return *m.LocalLoads
	}
	return 0
}

type Empty struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*TestMessage)(nil), "testpb.TestMessage")
	proto.RegisterType((*TestRequest)(nil), "testpb.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "testpb.TestResponse")
	proto.RegisterType((*CacheStats)(nil), "testpb.CacheStats")
	proto.RegisterType((*StatsResponse)(nil), "testpb.StatsResponse")
	proto.RegisterType((*Empty)(nil), "testpb.Empty")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x6a, 0xdb, 0x4e,
	0x10, 0xc6, 0x23, 0xdb, 0xf2, 0xdf, 0x1a, 0x39, 0xff, 0xc3, 0x36, 0x2d, 0x22, 0xa5, 0x24, 0x88,
	0x1c, 0x02, 0x05, 0x97, 0x18, 0x7a, 0xe9, 0xad, 0x84, 0xe0, 0x1a, 0x5a, 0x28, 0x4a, 0xee, 0x62,
	0xa3, 0x4e, 0x63, 0x81, 0xac, 0x55, 0x77, 0xc7, 0x6e, 0xfd, 0x40, 0x7d, 0xc0, 0xbe, 0x41, 0x99,
	0x19, 0x2b, 0x8d, 0x0b, 0xbd, 0xcd, 0xf7, 0x9b, 0x99, 0x4f, 0xdf, 0x6a, 0x17, 0x80, 0x30, 0xd0,
	0xac, 0xf3, 0x8e, 0x9c, 0x19, 0x73, 0xdd, 0xdd, 0xe7, 0x6f, 0x21, 0xbd, 0xc3, 0x40, 0x9f, 0x30,
	0x04, 0xfb, 0x80, 0xc6, 0xc0, 0xa8, 0xb5, 0x6b, 0xcc, 0xa2, 0xf3, 0xe8, 0x32, 0x29, 0xa4, 0x66,
	0x56, 0xd5, 0xb4, 0xcb, 0x06, 0xca, 0xb8, 0xce, 0x97, 0xba, 0x56, 0xe0, 0xb7, 0x0d, 0x06, 0x32,
	0x27, 0x10, 0x37, 0xee, 0x3b, 0xfa, 0x2c, 0x3a, 0x1f, 0x5c, 0x26, 0x85, 0x0a, 0x73, 0x01, 0x53,
	0x8f, 0x1d, 0x5a, 0x2a, 0x2b, 0xb7, 0x69, 0x49, 0x0c, 0xe2, 0x77, 0xd1, 0x55, 0x91, 0x2a, 0xbe,
	0x66, 0x9a, 0x5f, 0xc0, 0x54, 0xad, 0x42, 0xe7, 0xda, 0x80, 0xec, 0xb5, 0xb5, 0xcd, 0xa6, 0xcf,
	0xa0, 0x22, 0xff, 0x01, 0x70, 0x6d, 0xab, 0x15, 0xde, 0x92, 0xa5, 0xc0, 0x33, 0x35, 0xe1, 0x3a,
	0xc8, 0xcc, 0xb0, 0x50, 0xc1, 0xf4, 0x7e, 0x47, 0x18, 0xe4, 0x43, 0xc3, 0x42, 0x05, 0xc7, 0x7f,
	0x40, 0x0a, 0xd9, 0x50, 0xa0, 0xd4, 0xcc, 0x56, 0x35, 0x85, 0x6c, 0xa4, 0x8c, 0x6b, 0xf3, 0x02,
	0xc6, 0xb8, 0xad, 0x2b, 0x0a, 0x59, 0x2c, 0x74, 0xaf, 0xf2, 0x5f, 0x03, 0x38, 0x96, 0xaf, 0x3e,
	0x26, 0xec, 0x1d, 0xa3, 0x27, 0x8e, 0xaf, 0x00, 0x2a, 0xce, 0x57, 0x8a, 0xef, 0x54, 0x3a, 0x89,
	0x90, 0x0f, 0xb5, 0x06, 0xfe, 0x5a, 0x37, 0xcd, 0x63, 0x34, 0x11, 0xe6, 0x0c, 0x52, 0x72, 0x64,
	0x9b, 0xd2, 0x36, 0x8d, 0xab, 0x24, 0xe1, 0xa8, 0x00, 0x41, 0xef, 0x99, 0x98, 0x2b, 0x80, 0xb5,
	0xad, 0xdb, 0x52, 0x8c, 0x24, 0x6d, 0x3a, 0x37, 0x33, 0xbd, 0xba, 0xd9, 0x9f, 0xff, 0x51, 0x24,
	0x3c, 0x25, 0xda, 0xbc, 0x81, 0x64, 0xe5, 0x68, 0xbf, 0x11, 0xff, 0x73, 0x63, 0xb2, 0x72, 0xa4,
	0x0b, 0x2f, 0x21, 0x09, 0xe8, 0xb7, 0xe8, 0xcb, 0xba, 0xcd, 0xc6, 0x12, 0x6f, 0xa2, 0x60, 0xd9,
	0xea, 0xc5, 0xda, 0x2f, 0x21, 0x9b, 0x68, 0x6e, 0x11, 0x7c, 0xd8, 0x0e, 0xd1, 0x97, 0xda, 0x4a,
	0xf4, 0xb0, 0x4c, 0x3e, 0x4a, 0xfb, 0x0c, 0x52, 0x69, 0xa3, 0xf7, 0xce, 0x87, 0x0c, 0xa4, 0x2f,
	0x1b, 0x37, 0x42, 0x78, 0xa0, 0x71, 0x95, 0x6d, 0xf6, 0x06, 0xa9, 0x0e, 0x08, 0x12, 0x87, 0xfc,
	0x3f, 0x88, 0x6f, 0xd6, 0x1d, 0xed, 0xe6, 0x3f, 0x23, 0xf8, 0x7f, 0xe1, 0xdd, 0xa6, 0x93, 0xac,
	0xfc, 0x4e, 0xcc, 0x6b, 0x48, 0x96, 0x6d, 0x4d, 0x9f, 0x11, 0x7d, 0x30, 0xc7, 0xfd, 0xd1, 0x64,
	0xfc, 0xf4, 0x50, 0xe6, 0x47, 0x66, 0x0e, 0xc3, 0x05, 0x92, 0x79, 0xd6, 0xf3, 0x27, 0x8f, 0xf6,
	0xf4, 0xe4, 0x10, 0xea, 0xe5, 0xca, 0xce, 0x64, 0x81, 0x74, 0x7b, 0xc7, 0x0f, 0xed, 0x2f, 0xff,
	0xe7, 0xbd, 0x3c, 0x78, 0x10, 0xf9, 0xd1, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0xed, 0x1b,
	0x5d, 0x5b, 0x03, 0x00, 0x00,
}
